name: Markdown Meta
description: Read front-matter from Markdown files
runs:
  using: node16
  main: dist/index.js
branding:
  icon: edit-2
  color: orange
inputs:
  file:
    description: The file to read
    required: true
